### ISSUE TITLE
Bug: Bei Klick auf den Reiter Selectize

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/ui_tools#1]
![bildschirmfoto 2017-09-22 um 16 21 34](https://user-images.githubusercontent.com/791247/30748955-33a1018a-9fb2-11e7-9408-19609874f178.png)

**Comment by elricco** [comment]
Heruntergeladen aus dem Installer?

**Comment by skerbis** [comment]
0.2.3 aus dem Installer

**Comment by elricco** [comment]
Fehler gefixt, neu hochgeladen und veröffentlicht
