### ISSUE TITLE
Minicolors für Modernizr

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/ui_tools#16]
Hey, nur eine kleine kurze Info :) Die Minicolors für Modernizr werden von Haus aus nicht richtig geladen. Die Datei, die unter Assets liegt, wird anders geschrieben als die, die in der boot.php aufgerufen wird. Ist nur das Q in jQuery.

**Comment by skerbis** [comment]
Danke, minicolors for custimizer ist nun fixed in der aktuellen Beta
