### ISSUE TITLE
Initialisierung der Datepicker konfigurierbar machen

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/ui_tools#19]
Aktuell habe ich keine Chance irgendwas an den Datepickern zu konfigurieren: https://github.com/FriendsOfREDAXO/ui_tools/blob/master/plugins/bootstrap-datetimepicker/assets/bootstrap-datetimepicker/bootstrap-datetimepicker.js
Ich würde gerne eigene Konfigurationen hinterlegen können.

**Comment by skerbis** [comment]
@IngoWinter du könntest ein eigenes Initialisierungsskript verwenden.

**Comment by IngoWinter** [comment]
Wie kann ich denn verhindern, dass dein Skript geladen wird?

**Comment by skerbis** [comment]
Nimm doch ne andere .class? (Ist nicht mein Skript)

**Comment by IngoWinter** [comment]
Wenn ich andere Klassen nehme und mein eigenes Initialisierungsskript einbinde, macht das ui_tools Datepicker Plugin nichts mehr als 3 Assets zu laden (und die eingängigen Klassen wie `datepicker` zu blockieren). In dem Moment lade ich die 3 Assets lieber selbst flink da, wo ich auch mein Initialisierungsskript ablege...
