### ISSUE TITLE
Colorpicker: standardmäßig den Customizer unterstützen

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/ui_tools#2]
Entstanden aus diesem PR
https://github.com/redaxo/redaxo/pull/1369#issuecomment-332606466 

Vermutlich reicht es, die Standard-Konfiguration um die ID des Customizer-Feldes zu erweitern

**Comment by elricco** [comment]
Hi @cukabeka - zieh dir doch doch mal aus dem develop-Branch entweder alles oder nur das jquery-minicolors Plugin - sollte funktionieren. Und für die die den Colorpicker da nicht haben wollen kann er auch ausgemacht werden.

**Comment by cukabeka** [comment]
Hey @elricco - danke Dir fürs Einbauen! :) Habe in R5.4.0 nun die letzte Version der UI Tools installiert, leider kommt im Customizer kein Colorpicker. Wird die ID #customizer-labelcolor denn in der Colorpicker-Konfiguration aufgenommen, wenn ich das Häkchen in der backend-Einstellung setze?

**Comment by cukabeka** [comment]
Sehe gerade, dass der Browser 
assets/addons/ui_tools/plugins/jquery-minicolors/jquery-minicolors/jquery-minicolors-for-customizer.js 404 (Not Found)
ausgibt. Vermute gerade, dass die Install-Routine das JS nicht kopiert?

**Comment by elricco** [comment]
Doch, passiert ja automatisch. Ich sehe aber gerade, dass im Dateinamen das Q groß geschrieben ist. Ich ändere das mal und dann lade ich es gleich nochmal in den Installer.

**Comment by elricco** [comment]
@cukabeka Ist neu hochgeladen, bitte nochmal herunterladen und installieren / prüfen bittedankeschön :)

**Comment by cukabeka** [comment]
Ah, jetzt ja! Merci, funktioniert! @elricco 

Hatte übrigens einen Error, wenn ich von der älteren Version aktualisiert habe wegen "unexpected end of file" in update.php - falls jemand nochmal sowas melden sollte.
