### ISSUE TITLE
assets der Plugins fehlen bei frischer Installation

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/ui_tools#21]
Bei mir fehlten in einer frischen Redaxo und ui_tools Installation (Addon über Installer heruntergeladen) teilweise die Assets der Plugins:
/assets/addons/ui_tools/plugins/selectize/selectize/selectize.js
/assets/addons/ui_tools/plugins/jquery-minicolors/jquery-minicolors/jquery-minicolors.js

Scheint als ob der Build-Prozess nicht stattgefunden hätte. Dafür sind bei Selectize die ganzen src, build und test Ordner/Dateien da (grunt.js, package.json etc.). Unter /redaxo/src/addons/ui_tools/plugins/selectize/assets/selectize/ sieht's gleich aus.

**Comment by dtpop** [comment]
Hier auch - gleiches Phänomen. jquery-minicolors.js ist nicht da und dann startet minicolors nicht.

**Comment by skerbis** [comment]
Danke @dtpop @ynamite .. 
Ich denke das Addon muss mal neu. Hier wurden Vendoren und REDAXO js gemischt.
https://github.com/FriendsOfREDAXO/ui_tools/releases/tag/1.2.1
