### ISSUE TITLE
bootstrap-datetimepicker: SCSS.md und LESS.md existieren nicht mehr

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/ui_tools#27]
https://github.com/FriendsOfREDAXO/ui_tools/blob/507522c963a14360bbc12cd9b0c1f3922cb9b3ef/plugins/bootstrap-datetimepicker/pages/bootstrap-datetimepicker_scss.php#L6
https://github.com/FriendsOfREDAXO/ui_tools/blob/507522c963a14360bbc12cd9b0c1f3922cb9b3ef/plugins/bootstrap-datetimepicker/pages/bootstrap-datetimepicker_less.php#L6

Die beiden dort referenzierten Dateien existieren inzwischen nicht mehr in dem vendor-paket. 
Das führt in PHP 8.1 zu Deprecated-Notices, da im Anschluss dann `null` an Parsedown übergeben wird.

**Comment by eaCe** [comment]
Wurde inzwischen gefixt: https://github.com/FriendsOfREDAXO/ui_tools/commit/3f83984121d8698c629370a5fc87e3d462431746
