### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by dundunn** [FriendsOfREDAXO/ui_tools#7]
Sorry falls ich etwas übersehe, aber wie benutzt man dieses Addon? Ich würde gerne einen anderen colorpicker als den Standard verwenden, aber ich habe keine Ahnung, wie ich das mithilfe dieses Addons machen soll.

**Comment by skerbis** [comment]
Hi, zu jedem vendor findest du in der Readme einen Link.

**Comment by skerbis** [comment]
Die Doku, die du suchst ist demnach hier: https://labs.abeautifulsite.net/jquery-minicolors/

**Comment by dundunn** [comment]
Ich habe leider geringe Kenntnisse in Javascript und PHP. Ich bin davon ausgegangen, dass das Addon mir ermöglicht einfach einen MiniColors-Input in einem Modul zu erstellen ohne das JS und CSS einbinden zu müssen. 
Ich habe es aber bisher nur geschafft MiniColors einzubinden, indem ich das JS und CSS von Minicolors in das Modul eingebunden habe und bin nicht wirklich zufrieden damit. Ich weiß leider auch nicht, wie ich das ganze so einbinden kann, damit es immer im Backend zur Verfügung steht.

**Comment by elricco** [comment]
Hallo @dunnodun - ich hab es gerade auch nochmal geprüft - du musst deinem TextInput nur die Klasse `minicolors` hinzufügen und dann wird der Colorpicker im Backend geladen für den TextInput. Die CSS und JS Dateien werden bereits automatisch durch das Plugin des AddOns im Backend eingebunden.

**Comment by dundunn** [comment]
Hm dann funktioniert irgendetwas bei mir nicht. 
Mein Input sieht wie folgt aus: 
`<input class="form-control minicolors" name="REX_INPUT_VALUE[3]" value="#e0f3f1" type="text">`
Das Addon ist aktiv, aber dennoch wird mir nur ein Text-Input angezeigt: 
![Screenshot](https://i.imgur.com/tQIaLEy.png) 

Ich kriege es nur zum Laufen, wenn ich das hier vorher in das Modul einbinde 
```
<script src="/assets/cfg/jquery-minicolors/jquery.minicolors.js"></script>
<link rel="stylesheet" href="/assets/cfg/jquery-minicolors/jquery.minicolors.css">

<script>
  $(document).ready(function() {
    $('.minicolors').each(function() {
      $(this).minicolors({
        theme: 'bootstrap'
      });
    });
  });
</script>
```

**Comment by elricco** [comment]
Hi @dunnodun - ich habe deinen Code gerade in ein Modul bei mir gepackt und es funktioniert. Hast du das plugin `jquery-minicolors` des AddOns aktiviert?

**Comment by dundunn** [comment]
Oh man... Ich habe nicht gesehen, dass unter Addons Plugins sind. Vielen Dank an euch für die schnelle Hilfe und sorry, dass ich euch wegen meiner Blindheit belästigt habe ^^
